on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: get_token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.get_token.outputs.token }}

      - name: Excavate
        uses: ScoopInstaller/GithubActions@63f20efd5d6f876b16fbe2bc95428821b6051c0e # main
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
          USER_NAME: arama0517-dependency-updater[bot]
          USER_EMAIL: 279924183+arama0517-dependency-updater[bot]@users.noreply.github.com
