on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Excavate
        uses: ScoopInstaller/GithubActions@ec4ac4815ee2309cb47a239e66d959cbf8127b56 # main
        env:
          GITHUB_TOKEN: ${{ github.token }}
